# Site settings
title: "Sai Zhou"
description: "软件开发工程师 | Java | C++ | Android | HarmonyOS"
url: "https://saizhouX.github.io"
baseurl: ""

# User settings
username: "Sai Zhou"
user_title: "Software Engineer"
email: "lostsai82@gmail.com"
github_username: "SaiZhouX"

# Social Links (可根据需要添加更多)
social:
  - title: "github"
    url: "https://github.com/SaiZhouX"
  - title: "email"
    url: "mailto:lostsai82@gmail.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"